# Generated by Django 5.2.8 on 2025-12-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('country_code', models.CharField(choices=[('+91', '+91 (IND)'), ('+966', '+966 (SA)'), ('+1', '+1 (USA)'), ('+62', '+62 (IDN)'), ('+971', '+971 (UAE)')], default='+91', max_length=5)),
                ('mobile_number', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('allow_promotional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
